services:
    web:
        image: ghcr.io/sponja23/inventory-trading-websockets:latest
        ports:
            - "80:${PORT}"
        env_file:
            - .env
        restart: always
        command: 'sh -c "npm run start"'
